version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/lib/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/ui"
    schedule:
      interval: "weekly"
