{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.serviceName }}
  {{- if .Values.serviceAccount.clientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId | quote }}
  {{- end }}
{{- end }}
